version: '3.8'
services:
  spring-media-service:
    image: 69966/springgradleimg:1.1.1
    container_name: spring_cont_4
    ports:
      - "8083:8080"
    volumes:
      - "/mnt/nfs_shared:/app/src/main/resources/images"
    restart: always
